# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorganization_study_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='course_number',
            field=models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
    ]
