# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_courseorganization_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teacher_image/%Y/%m', verbose_name='\u6559\u5e08\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
