# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_teacher_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=20, verbose_name='\u5e74\u9f84'),
        ),
    ]
