# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='\u5e8f\u53f7')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='\u56fe\u7247')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'Banner',
                'verbose_name': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('send_type', models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
            options={
                'db_table': 'email',
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801',
            },
        ),
    ]
