# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d')),
                ('course_describe', models.CharField(max_length=500, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('course_detail', models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5')),
                ('course_degree', models.CharField(choices=[('height', '\u9ad8\u7ea7'), ('middle', '\u4e2d\u7ea7'), ('low', '\u4f4e\u7ea7')], max_length=10, verbose_name='\u8bfe\u7a0b\u96be\u5ea6')),
                ('learn_time', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f')),
                ('student', models.IntegerField(verbose_name='\u5b66\u751f\u4eba\u6570')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u8bfe\u7a0b\u56fe\u7247')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('students', models.IntegerField(verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('click_nums', models.IntegerField(verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8bfe\u7a0b\u5f00\u59cb\u65f6\u95f4')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8d44\u6599\u540d\u5b57')),
                ('download', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'course_resource',
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6599',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6599',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7ae0\u8282\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b\u5916\u952e')),
            ],
            options={
                'db_table': 'lesson',
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'db_table': 'video',
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
