# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('address', models.CharField(max_length=50, verbose_name='\u5730\u5740')),
                ('course', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b\u5916\u5efa')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
        ),
    ]
