# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180105_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default=b'', max_length=20, verbose_name='tag'),
        ),
    ]
