# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_teacher_age'),
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u6559\u5e08\u5916\u5efa'),
        ),
    ]
