# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180106_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_base',
            field=models.CharField(default=b'', max_length=100, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_learn',
            field=models.CharField(default=b'', max_length=100, verbose_name='\u8bfe\u7a0b\u4f60\u80fd\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
